
/*
GCD.cs

Copyright © 2018 Pluto Scarab Software. Most Rights Reserved.
Author: Bret Mulvey

This work is licensed under the Creative Commons Attribution-ShareAlike 4.0 International License. 
To view a copy of this license, visit http://creativecommons.org/licenses/by-sa/4.0/.

THIS IS AN AUTO-GENERATED SOURCE FILE. DO NOT EDIT THIS FILE DIRECTLY.
INSTEAD, EDIT THE .tt FILE WITH THE SIMILAR NAME AND RE-RUN THE TEXT TEMPLATING
FILE GENERATOR. IF YOU SAVE THE FILE IN VISUAL STUDIO IT WILL DO THIS FOR YOU.
*/

using System;
using System.Numerics;

namespace Foundations
{
    /// <summary>
    /// Number-theoretic functions.
    /// </summary>
	public static partial class Numbers
    {
        /// <summary>
        /// Greatest common divisor.
        /// </summary>
        public static sbyte GCD(sbyte p, sbyte q)
        {
            if (p == 0 || q == 0) return 0;
            (p, q) = (sbyte.Abs(p), sbyte.Abs(q));

            while (true)
            {
                var m = (sbyte)(p % q);
                if (m == 0) return q;
                p = q;
                q = m;
            }
        }

        /// <summary>
        /// Greatest common divisor.
        /// </summary>
        public static byte GCD(byte p, byte q)
        {
            if (p == 0 || q == 0) return 0;

            while (true)
            {
                var m = (byte)(p % q);
                if (m == 0) return q;
                p = q;
                q = m;
            }
        }

        /// <summary>
        /// Greatest common divisor.
        /// </summary>
        public static short GCD(short p, short q)
        {
            if (p == 0 || q == 0) return 0;
            (p, q) = (short.Abs(p), short.Abs(q));

            while (true)
            {
                var m = (short)(p % q);
                if (m == 0) return q;
                p = q;
                q = m;
            }
        }

        /// <summary>
        /// Greatest common divisor.
        /// </summary>
        public static ushort GCD(ushort p, ushort q)
        {
            if (p == 0 || q == 0) return 0;

            while (true)
            {
                var m = (ushort)(p % q);
                if (m == 0) return q;
                p = q;
                q = m;
            }
        }

        /// <summary>
        /// Greatest common divisor.
        /// </summary>
        public static int GCD(int p, int q)
        {
            if (p == 0 || q == 0) return 0;
            (p, q) = (int.Abs(p), int.Abs(q));

            while (true)
            {
                var m = (int)(p % q);
                if (m == 0) return q;
                p = q;
                q = m;
            }
        }

        /// <summary>
        /// Greatest common divisor.
        /// </summary>
        public static uint GCD(uint p, uint q)
        {
            if (p == 0 || q == 0) return 0;

            while (true)
            {
                var m = (uint)(p % q);
                if (m == 0) return q;
                p = q;
                q = m;
            }
        }

        /// <summary>
        /// Greatest common divisor.
        /// </summary>
        public static long GCD(long p, long q)
        {
            if (p == 0 || q == 0) return 0;
            (p, q) = (long.Abs(p), long.Abs(q));

            while (true)
            {
                var m = (long)(p % q);
                if (m == 0) return q;
                p = q;
                q = m;
            }
        }

        /// <summary>
        /// Greatest common divisor.
        /// </summary>
        public static ulong GCD(ulong p, ulong q)
        {
            if (p == 0 || q == 0) return 0;

            while (true)
            {
                var m = (ulong)(p % q);
                if (m == 0) return q;
                p = q;
                q = m;
            }
        }

        /// <summary>
        /// Greatest common divisor.
        /// </summary>
        public static BigInteger GCD(BigInteger p, BigInteger q)
        {
            if (p == 0 || q == 0) return 0;
            (p, q) = (BigInteger.Abs(p), BigInteger.Abs(q));

            while (true)
            {
                var m = (BigInteger)(p % q);
                if (m == 0) return q;
                p = q;
                q = m;
            }
        }

    }
}
