
/*
Fixed20p12.cs

Copyright © 2016 Pluto Scarab Software. Most Rights Reserved.
Author: Bret Mulvey

This work is licensed under the Creative Commons Attribution-ShareAlike 4.0 International License. 
To view a copy of this license, visit http://creativecommons.org/licenses/by-sa/4.0/.

THIS IS AN AUTO-GENERATED SOURCE FILE. DO NOT EDIT THIS FILE DIRECTLY.
INSTEAD, EDIT THE .tt FILE WITH THE SIMILAR NAME AND RE-RUN THE TEXT TEMPLATING
FILE GENERATOR. IF YOU SAVE THE FILE IN VISUAL STUDIO IT WILL DO THIS FOR YOU.
*/

using System;
using System.Globalization;
using Foundations.RandomNumbers;

namespace Foundations.Types
{
    /// <summary>
    /// Signed 32-bit number with 12 fractional bits and 20 integer bits.
    /// Represents values from -524288 to 524287.999755859375 in increments of 0.000244140625.
    /// </summary>
    public partial struct Fixed20p12 : IEquatable<Fixed20p12>, IComparable<Fixed20p12>
    {
        /// <summary>
        /// The constant value 0.
        /// </summary>
        public static readonly Fixed20p12 Zero = new Fixed20p12(0);

        /// <summary>
        /// The constant value 1.
        /// </summary>
        public static readonly Fixed20p12 One = new Fixed20p12(4096);

        /// <summary>
        /// The constant value -524288.
        /// </summary>
        public static readonly Fixed20p12 MinValue = new Fixed20p12(int.MinValue);

        /// <summary>
        /// The constant value 524287.999755859375.
        /// </summary>
        public static readonly Fixed20p12 MaxValue = new Fixed20p12(int.MaxValue);

        /// <summary>
        /// The constant value 0.000244140625.
        /// </summary>
        public static readonly Fixed20p12 ε = new Fixed20p12(1);

        /// <summary>PI</summary>
        public static readonly Fixed20p12 π          = (Fixed20p12)3.1415926535897932384626433833;

        /// <summary>Base of natural logarithm.</summary>
        public static readonly Fixed20p12 e          = (Fixed20p12)2.7182818284590452353602874714;

        /// <summary>Golden ratio.</summary>
        public static readonly Fixed20p12 φ          = (Fixed20p12)1.6180339887498948482045868344;

        /// <summary>Euler–Mascheroni constant.</summary>
        public static readonly Fixed20p12 γ          = (Fixed20p12)0.5772156649015328606065120901;

        /// <summary>Square root of 2π.</summary>
        public static readonly Fixed20p12 Sqrt2π     = (Fixed20p12)2.5066282746310005024157652848;

        /// <summary>Square root of 5.</summary>
        public static readonly Fixed20p12 Sqrt5      = (Fixed20p12)2.2360679774997896964091736687;

        /// <summary>Square root of π.</summary>
        public static readonly Fixed20p12 Sqrtπ      = (Fixed20p12)1.7724538509055160272981674833;

        /// <summary>Square root of 3.</summary>
        public static readonly Fixed20p12 Sqrt3      = (Fixed20p12)1.7320508075688772935274463415;

        /// <summary>Square root of 2.</summary>
        public static readonly Fixed20p12 Sqrt2      = (Fixed20p12)1.4142135623730950488016887242;

        /// <summary>Square root of π/2.</summary>
        public static readonly Fixed20p12 SqrtHalfπ  = (Fixed20p12)1.2533141373155002512078826424;

        /// <summary>Base-2 logarithm of 10.</summary>
        public static readonly Fixed20p12 Lg10       = (Fixed20p12)3.3219280948873623478703194295;
   
        /// <summary>Natural logarithm of 10.</summary>
        public static readonly Fixed20p12 Ln10       = (Fixed20p12)2.3025850929940456840179914547;

        /// <summary>Base-2 logarithm of e.</summary>
        public static readonly Fixed20p12 LgE        = (Fixed20p12)1.4426950408889634073599246810;
   
        /// <summary>Natural logarithm of 2.</summary>
        public static readonly Fixed20p12 Ln2        = (Fixed20p12)0.6931471805599453094172321215;

        /// <summary>Base-10 logarithm of e.</summary>
        public static readonly Fixed20p12 LogE       = (Fixed20p12)0.4342944819032518276511289189;

        /// <summary>Base-10 logarithm of 2.</summary>
        public static readonly Fixed20p12 Log2       = (Fixed20p12)0.3010299956639811952137388947;

        internal readonly int value;

        private Fixed20p12(int value)
        {
            this.value = value;
        }

        /// <summary>
        /// Parses a string representation of a <see cref="Fixed20p12"/>.
        /// </summary>
        public static Fixed20p12 Parse(string s)
        {
            var d = double.Parse(s);
            return new Fixed20p12((int)(d * 4096d + .5d * Math.Sign(d)));
        }

        /// <summary>
        /// Parses a string representation of a <see cref="Fixed20p12"/>.
        /// </summary>
        public static Fixed20p12 Parse(string s, IFormatProvider provider)
        {
            var d = double.Parse(s, provider);
            return new Fixed20p12((int)(d * 4096d + .5d * Math.Sign(d)));
        }

        /// <summary>
        /// Parses a string representation of a <see cref="Fixed20p12"/>.
        /// </summary>
        public static Fixed20p12 Parse(string s, NumberStyles style)
        {
            var d = double.Parse(s, style);
            return new Fixed20p12((int)(d * 4096d + .5d * Math.Sign(d)));
        }

        /// <summary>
        /// Parses a string representation of a <see cref="Fixed20p12"/>.
        /// </summary>
        public static Fixed20p12 Parse(string s, NumberStyles style, IFormatProvider provider)
        {
            var d = double.Parse(s, style, provider);
            return new Fixed20p12((int)(d * 4096d + .5d * Math.Sign(d)));
        }

        /// <summary>
        /// Tries to parse a string representation of a <see cref="Fixed20p12"/>.
        /// </summary>
        public static bool TryParse(string s, out Fixed20p12 result)
        {
            double d;
            
            if (!double.TryParse(s, out d))
            {
                result = Zero;
                return false;
            }

            result = new Fixed20p12((int)(d * 4096d + .5d * Math.Sign(d)));
            return true;
        }

        /// <summary>
        /// Tries to parse a string representation of a <see cref="Fixed20p12"/>.
        /// </summary>
        public static bool TryParse(string s, NumberStyles style, IFormatProvider provider, out Fixed20p12 result)
        {
            double d;
            
            if (!double.TryParse(s, style, provider, out d))
            {
                result = Zero;
                return false;
            }

            result = new Fixed20p12((int)(d * 4096d + .5d * Math.Sign(d)));
            return true;
        }

        /// <summary>
        /// Implementation of <see cref="object.ToString"/>.
        /// </summary>
        public override string ToString()
        {
            return (value * 0.000244140625d).ToString();
        }

        /// <summary>
        /// Gets a string representation of this <see cref="Fixed20p12"/>.
        /// </summary>
        public string ToString(string format)
        {
            return (value * 0.000244140625d).ToString(format);
        }

        /// <summary>
        /// Gets a string representation of this <see cref="Fixed20p12"/>.
        /// </summary>
        public string ToString(IFormatProvider provider)
        {
            return (value * 0.000244140625d).ToString(provider);
        }

        /// <summary>
        /// Gets a string representation of this <see cref="Fixed20p12"/>.
        /// </summary>
        public string ToString(string format, IFormatProvider provider)
        {
            return (value * 0.000244140625d).ToString(format, provider);
        }

        /// <summary>
        /// Explicitly converts a <see cref="Decimal"/> to a Fixed20p12.
        /// </summary>
        public static explicit operator Fixed20p12(decimal value)
        {
            if (value < -524288m || value > 524287.999755859375m) throw new ArgumentOutOfRangeException();
            return new Fixed20p12((int)(value * 4096m + .5m * Math.Sign(value)));
        }

        /// <summary>
        /// Implicitly converts a Fixed20p12 to a <see cref="Decimal"/>.
        /// </summary>
        public static implicit operator decimal(Fixed20p12 value)
        {
            return value.value * 0.000244140625m;
        }

        /// <summary>
        /// Explicitly converts a <see cref="Double"/> to a Fixed20p12.
        /// </summary>
        public static explicit operator Fixed20p12(double value)
        {
            if (value < -524288d || value > 524287.999755859375d) throw new ArgumentOutOfRangeException();
            return new Fixed20p12((int)(value * 4096d + .5d * Math.Sign(value)));
        }

        /// <summary>
        /// Implicitly converts a Fixed20p12 to a <see cref="Double"/>.
        /// </summary>
        public static implicit operator double(Fixed20p12 value)
        {
            return value.value * 0.000244140625d;
        }

        /// <summary>
        /// Explicitly converts a Fixed20p12 to a <see cref="Single"/>.
        /// </summary>
        public static explicit operator float(Fixed20p12 value)
        {
            return value.value * 0.000244140625f;
        }

        /// <summary>
        /// Implicitly converts a <see cref="Int64"/> to a Fixed20p12.
        /// </summary>
        public static implicit operator Fixed20p12(long value)
        {
            return new Fixed20p12((int)(value << 12));
        }

        /// <summary>
        /// Explicitly converts a Fixed20p12 to a <see cref="System.Int64"/>.
        /// </summary>
        public static explicit operator long(Fixed20p12 value)
        {
            return (long)(value.value >> 12);
        }

        /// <summary>
        /// Explicitly converts a Fixed20p12 to a <see cref="System.UInt64"/>.
        /// </summary>
        public static explicit operator ulong(Fixed20p12 value)
        {
            return (ulong)(value.value >> 12);
        }

        /// <summary>
        /// Explicitly converts a Fixed20p12 to a <see cref="System.Int32"/>.
        /// </summary>
        public static explicit operator int(Fixed20p12 value)
        {
            return (int)(value.value >> 12);
        }

        /// <summary>
        /// Explicitly converts a Fixed20p12 to a <see cref="System.UInt32"/>.
        /// </summary>
        public static explicit operator uint(Fixed20p12 value)
        {
            return (uint)(value.value >> 12);
        }

        /// <summary>
        /// Explicitly converts a Fixed20p12 to a <see cref="System.Int16"/>.
        /// </summary>
        public static explicit operator short(Fixed20p12 value)
        {
            return (short)(value.value >> 12);
        }

        /// <summary>
        /// Explicitly converts a Fixed20p12 to a <see cref="System.UInt16"/>.
        /// </summary>
        public static explicit operator ushort(Fixed20p12 value)
        {
            return (ushort)(value.value >> 12);
        }

        /// <summary>
        /// Explicitly converts a Fixed20p12 to a <see cref="System.SByte"/>.
        /// </summary>
        public static explicit operator sbyte(Fixed20p12 value)
        {
            return (sbyte)(value.value >> 12);
        }

        /// <summary>
        /// Explicitly converts a Fixed20p12 to a <see cref="System.Byte"/>.
        /// </summary>
        public static explicit operator byte(Fixed20p12 value)
        {
            return (byte)(value.value >> 12);
        }

        /// <summary>
        /// Implementation of <see cref="object.Equals(object)"/>.
        /// </summary>
        public override bool Equals(object obj)
        {
            return obj is Fixed20p12 && Equals((Fixed20p12)obj);
        }

        /// <summary>
        /// Implementation of <see cref="IEquatable{Fixed20p12}"/>.
        /// </summary>
        public bool Equals(Fixed20p12 other)
        {
            return value == other.value;
        }

        /// <summary>
        /// Equality operator.
        /// </summary>
        public static bool operator ==(Fixed20p12 a, Fixed20p12 b)
        {
            return a.value == b.value;
        }

        /// <summary>
        /// Inequality operator.
        /// </summary>
        public static bool operator !=(Fixed20p12 a, Fixed20p12 b)
        {
            return a.value != b.value;
        }

        /// <summary>
        /// Implementation of <see cref="object.GetHashCode"/>.
        /// </summary>
        public override int GetHashCode()
        {
            return value ^ -1985174358;
        }

        /// <summary>
        /// Less-than operator.
        /// </summary>
        public static bool operator <(Fixed20p12 a, Fixed20p12 b)
        {
            return a.value < b.value;
        }

        /// <summary>
        /// Greater-than operator.
        /// </summary>
        public static bool operator >(Fixed20p12 a, Fixed20p12 b)
        {
            return a.value > b.value;
        }

        /// <summary>
        /// Less-than-or-equal operator.
        /// </summary>
        public static bool operator <=(Fixed20p12 a, Fixed20p12 b)
        {
            return a.value <= b.value;
        }

        /// <summary>
        /// Greater-than-or-equal operator.
        /// </summary>
        public static bool operator >=(Fixed20p12 a, Fixed20p12 b)
        {
            return a.value >= b.value;
        }

        /// <summary>
        /// Implementation of <see cref="IComparable{Fixed20p12}"/>.
        /// </summary>
        public int CompareTo(Fixed20p12 other)
        {
            return value.CompareTo(other.value);
        }

        /// <summary>
        /// Right-shift operator.
        /// </summary>
        public static Fixed20p12 operator >>(Fixed20p12 value, int shift)
        {
            return new Fixed20p12((int)(value.value >> shift));
        }

        /// <summary>
        /// Left-shift operator.
        /// </summary>
        public static Fixed20p12 operator <<(Fixed20p12 value, int shift)
        {
            return new Fixed20p12((int)(value.value << shift));
        }

        /// <summary>
        /// Gets the underlying bits that represent this <see cref="Fixed20p12"/>.
        /// </summary>
        public static int ToInt32Bits(Fixed20p12 value)
        {
            return value.value;
        }

        /// <summary>
        /// Creates a <see cref="Fixed20p12"/> from the underlying bit representation.
        /// </summary>
        public static Fixed20p12 FromInt32Bits(int value)
        {
            return new Fixed20p12(value);
        }

        /// <summary>
        /// Unary plus operator.
        /// </summary>
        public static Fixed20p12 operator +(Fixed20p12 value)
        {
            return value;
        }

        /// <summary>
        /// Unary minus operator.
        /// </summary>
        public static Fixed20p12 operator -(Fixed20p12 value)
        {
            return new Fixed20p12((int)(-value.value));
        }

        /// <summary>
        /// Increment operator.
        /// </summary>
        public static Fixed20p12 operator ++(Fixed20p12 value)
        {
            return value + One;
        }

        /// <summary>
        /// Decrement operator.
        /// </summary>
        public static Fixed20p12 operator --(Fixed20p12 value)
        {
            return value - One;
        }

        /// <summary>
        /// Addition operator.
        /// </summary>
        public static Fixed20p12 operator +(Fixed20p12 a, Fixed20p12 b)
        {
            return new Fixed20p12((int)(a.value + b.value));
        }

        /// <summary>
        /// Subtraction operator.
        /// </summary>
        public static Fixed20p12 operator -(Fixed20p12 a, Fixed20p12 b)
        {
            return new Fixed20p12((int)(a.value - b.value));
        }

        /// <summary>
        /// Multiplication operator.
        /// </summary>
        public static Fixed20p12 operator *(Fixed20p12 a, Fixed20p12 b)
        {
            return new Fixed20p12((int)(((long)a.value * (long)b.value + ((long)1 << 11)) >> 12));
        }

        /// <summary>
        /// Division operator.
        /// </summary>
        public static Fixed20p12 operator /(Fixed20p12 a, Fixed20p12 b)
        {
            return new Fixed20p12((int)((((long)a.value << 32) / b.value) >> 20));
        }

        /// <summary>
        /// Explicitly cast a <see cref="Fixed4p28"/> to a <see cref="Fixed20p12"/>.
        /// </summary>
        public static explicit operator Fixed20p12(Fixed4p28 other)
        {
            return new Fixed20p12((int)(other.value >> 16));
        }

        /// <summary>
        /// Explicitly cast a <see cref="Fixed8p24"/> to a <see cref="Fixed20p12"/>.
        /// </summary>
        public static explicit operator Fixed20p12(Fixed8p24 other)
        {
            return new Fixed20p12((int)(other.value >> 12));
        }

        /// <summary>
        /// Explicitly cast a <see cref="Fixed12p20"/> to a <see cref="Fixed20p12"/>.
        /// </summary>
        public static explicit operator Fixed20p12(Fixed12p20 other)
        {
            return new Fixed20p12((int)(other.value >> 8));
        }

        /// <summary>
        /// Explicitly cast a <see cref="Fixed16p16"/> to a <see cref="Fixed20p12"/>.
        /// </summary>
        public static explicit operator Fixed20p12(Fixed16p16 other)
        {
            return new Fixed20p12((int)(other.value >> 4));
        }

        /// <summary>
        /// Explicitly cast a <see cref="Fixed24p8"/> to a <see cref="Fixed20p12"/>.
        /// </summary>
        public static explicit operator Fixed20p12(Fixed24p8 other)
        {
            if (other.value < -134217728 || other.value > 134217727) throw new ArgumentOutOfRangeException();
            return new Fixed20p12((int)(other.value << 4));
        }

        /// <summary>
        /// Explicitly cast a <see cref="Fixed28p4"/> to a <see cref="Fixed20p12"/>.
        /// </summary>
        public static explicit operator Fixed20p12(Fixed28p4 other)
        {
            if (other.value < -8388608 || other.value > 8388607) throw new ArgumentOutOfRangeException();
            return new Fixed20p12((int)(other.value << 8));
        }

        /// <summary>
        /// Gets the absolute value of a <see cref="Fixed20p12"/>.
        /// </summary>
        public static Fixed20p12 Abs(Fixed20p12 value)
        {
            return new Fixed20p12(Math.Abs(value.value));
        }

        /// <summary>
        /// Gets the absolute value of this <see cref="Fixed20p12"/>.
        /// </summary>
        public Fixed20p12 Abs()
        {
            return new Fixed20p12(Math.Abs(value));
        }

        /// <summary>
        /// Gets the greatest integer <see cref="Fixed20p12"/> that is not greater than the specified value.
        /// </summary>
        public static Fixed20p12 Floor(Fixed20p12 value)
        {
            return new Fixed20p12((int)(value.value & 0xFFFFF000));
        }

        /// <summary>
        /// Gets the greatest integer <see cref="Fixed20p12"/> that is not greater than this value.
        /// </summary>
        public Fixed20p12 Floor()
        {
            return new Fixed20p12((int)(value & 0xFFFFF000));
        }

        /// <summary>
        /// Gets the least integer <see cref="Fixed20p12"/> that is not less than the specified value.
        /// </summary>
        public static Fixed20p12 Ceiling(Fixed20p12 value)
        {
            return new Fixed20p12((int)((value.value + 0xFFF) & 0xFFFFF000));
        }

        /// <summary>
        /// Gets the least integer <see cref="Fixed20p12"/> that is not less than this value.
        /// </summary>
        public Fixed20p12 Ceiling()
        {
            return new Fixed20p12((int)((value + 0xFFF) & 0xFFFFF000));
        }

        /// <summary>
        /// Gets the nearest integer <see cref="Fixed20p12"/> to the specified value.
        /// </summary>
        public static Fixed20p12 Round(Fixed20p12 value)
        {
            return new Fixed20p12((int)((value.value + 0x800) & 0xFFFFF000));
        }

        /// <summary>
        /// Gets the nearest integer <see cref="Fixed20p12"/> to this value.
        /// </summary>
        public Fixed20p12 Round()
        {
            return new Fixed20p12((int)((value + 0x800) & 0xFFFFF000));
        }

        /// <summary>
        /// Gets the fractional portion of a <see cref="Fixed20p12"/>.
        /// </summary>
        public static Fixed20p12 Frac(Fixed20p12 value)
        {
            return new Fixed20p12((int)(Math.Abs(value.value) & 0xFFF));
        }

        /// <summary>
        /// Gets the fractional portion of this <see cref="Fixed20p12"/>.
        /// </summary>
        public Fixed20p12 Frac()
        {
            return new Fixed20p12((int)(Math.Abs(value) & 0xFFF));
        }

        /// <summary>
        /// Rounds a <see cref="Fixed20p12"/> toward zero.
        /// </summary>
        public static Fixed20p12 Truncate(Fixed20p12 value)
        {
            return value.value >= 0 ? Floor(value) : Ceiling(value);
        }

        /// <summary>
        /// Rounds this <see cref="Fixed20p12"/> toward zero.
        /// </summary>
        public Fixed20p12 Truncate()
        {
            return value >= 0 ? Floor() : Ceiling();
        }

        /// <summary>
        /// Gets the sign of a <see cref="Fixed20p12"/>.
        /// </summary>
        public static int Sign(Fixed20p12 value)
        {
            return Math.Sign(value.value);
        }

        /// <summary>
        /// Gets the sign of this <see cref="Fixed20p12"/>.
        /// </summary>
        public int Sign()
        {
            return Math.Sign(value);
        }

        /// <summary>
        /// Gets the lesser of two <see cref="Fixed20p12"/> values.
        /// </summary>
        public static Fixed20p12 Min(Fixed20p12 a, Fixed20p12 b)
        {
            return a.value < b.value ? a : b;
        }

        /// <summary>
        /// Gets the greater of two <see cref="Fixed20p12"/> values.
        /// </summary>
        public static Fixed20p12 Max(Fixed20p12 a, Fixed20p12 b)
        {
            return a.value > b.value ? a : b;
        }

        /// <summary>
        /// Acos function.
        /// </summary>
        public static Fixed20p12 Acos(Fixed20p12 x) => (Fixed20p12)Math.Acos((double)x);

        /// <summary>
        /// Acos function.
        /// </summary>
        public Fixed20p12 Acos() => (Fixed20p12)Math.Acos((double)this);

        /// <summary>
        /// Asin function.
        /// </summary>
        public static Fixed20p12 Asin(Fixed20p12 x) => (Fixed20p12)Math.Asin((double)x);

        /// <summary>
        /// Asin function.
        /// </summary>
        public Fixed20p12 Asin() => (Fixed20p12)Math.Asin((double)this);

        /// <summary>
        /// Atan function.
        /// </summary>
        public static Fixed20p12 Atan(Fixed20p12 x) => (Fixed20p12)Math.Atan((double)x);

        /// <summary>
        /// Atan function.
        /// </summary>
        public Fixed20p12 Atan() => (Fixed20p12)Math.Atan((double)this);

        /// <summary>
        /// Cos function.
        /// </summary>
        public static Fixed20p12 Cos(Fixed20p12 x) => (Fixed20p12)Math.Cos((double)x);

        /// <summary>
        /// Cos function.
        /// </summary>
        public Fixed20p12 Cos() => (Fixed20p12)Math.Cos((double)this);

        /// <summary>
        /// Cosh function.
        /// </summary>
        public static Fixed20p12 Cosh(Fixed20p12 x) => (Fixed20p12)Math.Cosh((double)x);

        /// <summary>
        /// Cosh function.
        /// </summary>
        public Fixed20p12 Cosh() => (Fixed20p12)Math.Cosh((double)this);

        /// <summary>
        /// Exp function.
        /// </summary>
        public static Fixed20p12 Exp(Fixed20p12 x) => (Fixed20p12)Math.Exp((double)x);

        /// <summary>
        /// Exp function.
        /// </summary>
        public Fixed20p12 Exp() => (Fixed20p12)Math.Exp((double)this);

        /// <summary>
        /// Log10 function.
        /// </summary>
        public static Fixed20p12 Log10(Fixed20p12 x) => (Fixed20p12)Math.Log10((double)x);

        /// <summary>
        /// Log10 function.
        /// </summary>
        public Fixed20p12 Log10() => (Fixed20p12)Math.Log10((double)this);

        /// <summary>
        /// Sin function.
        /// </summary>
        public static Fixed20p12 Sin(Fixed20p12 x) => (Fixed20p12)Math.Sin((double)x);

        /// <summary>
        /// Sin function.
        /// </summary>
        public Fixed20p12 Sin() => (Fixed20p12)Math.Sin((double)this);

        /// <summary>
        /// Sinh function.
        /// </summary>
        public static Fixed20p12 Sinh(Fixed20p12 x) => (Fixed20p12)Math.Sinh((double)x);

        /// <summary>
        /// Sinh function.
        /// </summary>
        public Fixed20p12 Sinh() => (Fixed20p12)Math.Sinh((double)this);

        /// <summary>
        /// Sqrt function.
        /// </summary>
        public static Fixed20p12 Sqrt(Fixed20p12 x) => (Fixed20p12)Math.Sqrt((double)x);

        /// <summary>
        /// Sqrt function.
        /// </summary>
        public Fixed20p12 Sqrt() => (Fixed20p12)Math.Sqrt((double)this);

        /// <summary>
        /// Tan function.
        /// </summary>
        public static Fixed20p12 Tan(Fixed20p12 x) => (Fixed20p12)Math.Tan((double)x);

        /// <summary>
        /// Tan function.
        /// </summary>
        public Fixed20p12 Tan() => (Fixed20p12)Math.Tan((double)this);

        /// <summary>
        /// Tanh function.
        /// </summary>
        public static Fixed20p12 Tanh(Fixed20p12 x) => (Fixed20p12)Math.Tanh((double)x);

        /// <summary>
        /// Tanh function.
        /// </summary>
        public Fixed20p12 Tanh() => (Fixed20p12)Math.Tanh((double)this);

        /// <summary>
        /// Gets a random <see cref="Fixed20p12"/> from 0 (inclusive) to 1 (exclusive).
        /// </summary>
        public static Fixed20p12 Random(Generator g)
        {
            return new Fixed20p12(g.Int32(4096));
        }
    }
}